services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
  db:
    image: postgres:15
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: secure_docs
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: